[OneExplorer] Do not use useless return
Samsung/ONE-vscode pull request #1031
Opened 2022-07-13 12:52 UTC by llFreetimell

`vscode.workspace.fs.delete` returns `Thenable<void>`, so `return` is useless.
This commit removes this.

ONE-vscode-DCO-1.0-Signed-off-by: Seok NamKoong <seok9311@naver.com>

2022-07-14 01:37 UTC, jyoungyun approved these changes
LGTM

2022-07-14 02:53 UTC, dayo09 approved these changes

2022-07-14 02:55 UTC, dayo09 commented
Q. Is it not recommended to use useless return? Because, for the code consistencies, most filesystem jobs returns promise. And I thought it's consistent to return the void promise, it's handy to add something else in the future. And some language recommends using return to make sure the function's exit point

2022-07-14 06:25 UTC, llFreetimell commented
> most filesystem jobs returns promise. And I thought it's consistent to return the void promise

Ah, I am sorry for confusion.
Original warning was inconsistent return statement.

```ts
    vscode.window.showInformationMessage(title, {detail: detail, modal: true}, approval)
        .then(ans => {
          if (ans === approval) {
            Logger.info('OneExplorer', `Delete '${oneNode.node.name}'.`);
            return vscode.workspace.fs.delete(
                oneNode.node.uri, {recursive: recursive, useTrash: true});
            // return Promise<void>
          }
          // return void
        })
        .then(() => this.refresh());
```

As you can see above, the lambda function returns both `void` and `Promise<void>`.
I was to fix this, but I think your question makes sense.
What should I change `// return void` to? :D

2022-07-14 07:36 UTC, dayo09 commented
@llFreetimell Oh I thought it was returning from the most outer function. I read the change again and found out this change will make a bug. Let me explain in the code.

2022-07-14 07:37 UTC, dayo09 requested changes

2022-07-14 07:37 UTC, dayo09 commented on src/OneExplorer/OneExplorer.ts
> +            vscode.workspace.fs.delete(oneNode.node.uri, {recursive: recursive, useTrash: true});
Please do not remove `return` here as it must return a promise to let the next then phrase know that the promise was done.

2022-07-14 07:38 UTC, dayo09 commented on src/OneExplorer/OneExplorer.ts
>            }
If you want to make the return type consistent, then it's better to return a resolved promise of void type outside the if statement.

2022-07-14 07:42 UTC, dayo09 commented on src/OneExplorer/OneExplorer.ts
> +            vscode.workspace.fs.delete(oneNode.node.uri, {recursive: recursive, useTrash: true});
OR, 

```suggestion
            vscode.workspace.fs.delete(oneNode.node.uri, {recursive: recursive, useTrash: true}).then(()=>this.refresh());
```

This looks better then adding a resolved Promise<void>

2022-07-14 09:03 UTC, dayo09 approved these changes

2022-07-15 00:43 UTC, llFreetimell commented
@jyoungyun 

Since this PR is simple and original author validated this PR, I will merge this!

2022-07-15 00:43 UTC, merged