[EdgeTPU] Add files for .edgetpucfg
Samsung/ONE-vscode pull request #1671
Opened 2023-09-22 05:17 UTC by hohee-hee

Related to #1621,

for modularization of EdgeTPU, we decided to add a new file name extension for config file for edgetpu compiler.
Its name is 'edgetpucfg'.

'edgetpucfg' has different steps and options than the original cfg file.
Therefore, this commit adds a new directory and files for `.edgetpucfg` in /media/EdgetpuCfgEditor.

ONE-vscode-DCO-1.0-Signed-off-by: hohee-hee [khappy517@gmail.com](mailto:khappy517@gmail.com)

2023-09-25 02:58 UTC, jyoungyun commented
Please clean up your commits. :)

2023-09-25 03:13 UTC, dayo09 commented
I will review this PR when the rest of parts are merged so that the panel can be opened in UI.

2023-09-26 04:30 UTC, Hyeon-Uk requested changes

2023-09-26 04:30 UTC, Hyeon-Uk commented on media/EdgeTPUCfgEditor/vscodeapi.js
> + * Copyright (c) 2022 Samsung Electronics Co., Ltd. All Rights Reserved
```suggestion
 * Copyright (c) 2023 Samsung Electronics Co., Ltd. All Rights Reserved
```

i think this line should be changed

2023-10-02 04:52 UTC, dayo09 commented
![image](https://github.com/Samsung/ONE-vscode/assets/17171963/7a9a81e2-06ac-481c-a3df-21eb3b329ffc)

👍 

I checked these working well:
- Changing 'Input Path'
  - makes the same change on text viewer.
  - fills 'Output Path' accordingly
- Filling in Intermediate_tensors / Checking 'Show Operations'
  - makes the same change on text viewer
- Checking 'Search Delegate'
  - makes the same change on text viewer
  - shows 'Delegate Search Step' well

2023-10-02 04:53 UTC, dayo09 approved these changes
LGTM, good works :-D Thanks!

2023-10-02 06:15 UTC, Hyeon-Uk approved these changes
Good :-)

2023-10-02 13:17 UTC, rhqjatn2398 approved these changes
LGTM 👍

2023-10-03 07:39 UTC, merged